import torch


def get_image(
    image,
    transforms,
    debug=False
):
    """Lightwieght Dataset+Dataloader

    Args:
        image (cv2.Image): this is the image uploaded from the `file_uploader`
        transforms (A.compose): transformations to be applied to the image

    Returns:
        numpy.array: the prediction of the model on the image uploaded
    """
    if debug:
        print('~:~:~preprocessing the image')
    image = transforms(image=image)
    return image


def infer_once(image, transforms, model, debug=False):
    """Makes prediction on the arg:`image` once

    Args:
        image (cv2.image): image to be predicted Benign or Malignant
        transforms (A.compose): the transforms to be applied to arg:`image`
        before passing it to the cnn
        model (torch.nn.Module): trained cnn
        debug (bool, optional): Debug flag. Defaults to False.

    Returns:
        np.array: predictions generated by the model on arg:`image`
    """
    if debug:
        print('~:~:~making predictions x1')
    image = get_image(
        image=image,
        transforms=transforms,
        debug=debug,
    )['image']
    model.eval()

    prediction = torch.sigmoid(model(image.unsqueeze(dim=0))).detach()
    return prediction.numpy()
